# Generated by Django 4.2.4 on 2023-10-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0004_custom_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='def.png', null=True, upload_to='prof_pic/'),
        ),
    ]
